PWN-6090 - make a warning screen when address does not have account
p2p-org/p2p-wallet-android pull request #1014
Opened 2022-12-09 16:15 UTC by kabramovp2p

## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-6090

## Description of Work

PWN-6090 - make a warning screen when address does not have account

2022-12-09 16:34 UTC, gslevinkov commented
any screen shots please?

2022-12-11 13:17 UTC, kabramovp2p commented
оукай

2022-12-12 08:16 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/newsend/noaccount/SendNoAccountFragment.kt
> +    private val criticalIssue: Boolean by args(ARG_CRITICAL_ISSUE)
dknow why not?

2022-12-12 08:17 UTC, kabramovp2p commented on app/src/main/res/values/send_strings.xml
> +    <string name="send_no_account_non_critical_message">You will have to pay a one-time fee (~$0.03) to create a %s account for this address. You can choose in which currency to pay with below.</stri
it is not related to strings it is related to buttons
when you can switch token or not

2022-12-12 11:08 UTC, davran1001 approved these changes

2022-12-12 11:50 UTC, gslevinkov requested changes

2022-12-12 11:50 UTC, gslevinkov commented on app/src/main/res/layout/fragment_send_no_account.xml
> +            android:id="@+id/buttonSwitch"
buttonSwitch -> buttonSwitchToken

2022-12-12 11:50 UTC, gslevinkov commented on app/src/main/res/layout/fragment_send_no_account.xml
> +            android:id="@+id/buttonSwitch"
can't see click listeners for this button

2022-12-12 11:51 UTC, gslevinkov approved these changes

2022-12-12 12:15 UTC, merged