Feature/UI reserving username
p2p-org/p2p-wallet-android pull request #119
Opened 2021-09-29 10:07 UTC by EugeneRogov

2021-09-29 10:12 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/ui/username/ReservingUsernameFragment.kt
> +            writeFeedbackText.setSpan(clickableSpan, 12, 27, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
У нас будет поддержка разных языков, и на других языках у тебя сломается вот это место, поэтому надо бы переделать

2021-09-29 10:12 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/ui/security/SecurityKeyFragment.kt
> +//        replaceFragment(CreatePinFragment.create(PinLaunchMode.CREATE))
Кажется забыл вернуть старый флоу здесь

2021-09-29 10:13 UTC, 1sakov commented on app/src/main/res/drawable/ic_lamp.xml
> +      android:fillColor="#00000000"
При темной теме иконка не будет видна, заюзай цвета из темы

2021-09-29 10:14 UTC, 1sakov commented on app/src/main/res/layout/fragment_reserving_username.xml
> +            android:layout_marginEnd="16dp"
Предлагаю использовать `marginHorizontal` чтобы уменьшить количество параметров

2021-09-29 10:19 UTC, 1sakov requested changes

2021-09-29 10:19 UTC, 1sakov commented on app/src/main/res/layout/fragment_reserving_username.xml
> +            android:paddingBottom="16dp"
Аналогично здесь. 
`paddingHorizontal`, `paddingVertical`

2021-09-29 10:19 UTC, 1sakov commented on app/src/main/res/layout/fragment_reserving_username.xml
> +            android:id="@+id/usernameInput"
В итоге, давай договоримся, либо etUsername, tvUsername и прочие префиксы, либо называть как сейчас. 
Здесь уже третий вариант названий появляется

2021-09-29 10:19 UTC, 1sakov commented on app/src/main/res/layout/fragment_reserving_username.xml
> +            android:inputType="numberDecimal"
Здесь не `text`?

2021-09-29 10:19 UTC, 1sakov commented on app/src/main/res/layout/fragment_reserving_username.xml
> +            android:layout_marginStart="16dp"
Здесь и в других местах

2021-09-29 10:25 UTC, EugeneRogov commented on app/src/main/java/com/p2p/wallet/auth/ui/username/ReservingUsernameFragment.kt
> +            writeFeedbackText.setSpan(clickableSpan, 12, 27, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
Тогда несколько TextView для этой строки. Если нет др. предложений?

2021-09-29 10:37 UTC, EugeneRogov commented on app/src/main/res/layout/fragment_reserving_username.xml
> +            android:id="@+id/usernameInput"
Оставим твой вариант

2021-09-29 10:49 UTC, EugeneRogov commented on app/src/main/res/layout/fragment_reserving_username.xml
> +            android:layout_marginEnd="16dp"
при marginHorizontal отступы у bgView съезжают

2021-09-29 11:10 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/ui/username/ReservingUsernameFragment.kt
> +            writeFeedbackText.setSpan(clickableSpan, 12, 27, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)
есть такое решение: 
```
private fun buildClickableMessage(): SpannableString {
        val clickableText = getString(R.string.clickable_text)
        val message = getString(R.string.general_error_message, clickableText)
        val span = SpannableString(message)

        /*
         * Applying clickable span for number
         * */
        val clickableNumber = object : ClickableSpan() {
            override fun onClick(widget: View) {
                // do smth
            }
        }

        val start = span.indexOf(clickableText)
        val end = span.indexOf(clickableText) + clickableText.length
        span.setSpan(clickableNumber, start, end, Spanned.SPAN_INCLUSIVE_INCLUSIVE)

        return span
    }```

2021-09-29 13:46 UTC, EugeneRogov commented on app/src/main/res/drawable/ic_lamp.xml
> +      android:fillColor="#00000000"
проверил на обеих темах, все видно

2021-09-29 13:47 UTC, EugeneRogov commented on app/src/main/res/layout/fragment_reserving_username.xml
> +            android:inputType="numberDecimal"
done

2021-09-29 13:50 UTC, EugeneRogov commented on app/src/main/java/com/p2p/wallet/auth/ui/security/SecurityKeyFragment.kt
> +//        replaceFragment(CreatePinFragment.create(PinLaunchMode.CREATE))
Старый флоу открывает пока pincode

2021-09-30 09:21 UTC, 1sakov approved these changes
Оставил один маленький комментарий. А в целом, все четко!

2021-09-30 09:21 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/ui/username/ReservingUsernameFragment.kt
> +    private fun skipThisStepClickable(): SpannableString {
Давай назовем метод так, чтобы было понятно что он делает. Заюзаем что-то вроде buildClickableText, getClickableText и т.д. 
А то по текущему названию кажется что он пропускает какой-то шаг в коде

2021-09-30 10:00 UTC, merged