Feature/api reserving username
p2p-org/p2p-wallet-android pull request #122
Opened 2021-10-01 07:49 UTC by EugeneRogov

2021-10-04 11:57 UTC, 1sakov requested changes

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/api/UsernameApi.kt
> +    @POST("name_register/{username}")
В аргументах нет параметра `@Path`, полагаю нужно откорректировать эндпоинт.

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/api/UsernameCheckResponse.kt
> +    @SerializedName("class") val class_: String,
Может `clazz`?

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/interactor/ReservingUsernameInteractor.kt
> +    suspend fun checkUsername(username: String): UsernameCheckResponse = withContext(Dispatchers.IO) {
Ретрофит итак запускает запрос на заднем фоне, здесь `withContext(Dispatchers.IO)` лишний

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/interactor/ReservingUsernameInteractor.kt
> +                owner = "",
А почему здесь параметры пустые?

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/model/NameRegisterBody.kt
> +data class NameRegisterBody(
Предлагаю добавлять `response` постфикс на все API модели

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/model/NameRegisterBody.kt
> +    data class Credentials(
Думаю здесь лучше класс создать вне `NameRegisterBody`

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/repository/UsernameRepository.kt
> +    suspend fun usernameCheck(username: String): UsernameCheckResponse
Предлагаю `checkUsername`

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/repository/UsernameRepository.kt
> +    suspend fun usernameRegister(body: NameRegisterBody): String
Предлагаю `registerUsername`

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/ui/username/ReservingUsernameFragment.kt
> +            usernameEditText.addTextChangedListener(object : TextWatcher {
`usernameEditText.doAfterTextChanged { 
         presenter.checkUsername(it.toString())
 }
`

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/ui/username/ReservingUsernamePresenter.kt
> +    var checkUsernameJob: Job? = null
`private`

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/ui/username/ReservingUsernamePresenter.kt
> +            interactor.registerUsername()
Думаю даже если нет пока интерсептора, нужно обернуть в try/catch и показать ошибку по умолчанию, иначе у нас будет крашиться в этом месте

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/ui/username/ReservingUsernamePresenter.kt
> +        checkUsernameJob = launch {
Давай добавим `delay`, где-то 200-250 мс

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/res/values/environment_config.xml
> +    <string name="solanaUsername">https://fee-relayer.solana.p2p.org/</string>
Эта переменная не нужна, ретрофит уже создан, и ресурс в этом же файлике есть `feeRelayerBaseUrl`

2021-10-04 11:57 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/AuthModule.kt
> +    private const val RESERVING_USERNAME_QUALIFIER = "https://fee-relayer.solana.p2p.org"
Я не уверен, что `qualifier` нужно называть в точности как ссылка. Нам ведь главное тут нужна индивидуальность тэга. Я обычно использую без `https`, но тут по желанию.

2021-10-04 13:38 UTC, EugeneRogov commented on app/src/main/java/com/p2p/wallet/auth/interactor/ReservingUsernameInteractor.kt
> +                owner = "",
Пока просто заглушка. Эти данные я получи из капчи

2021-10-04 13:55 UTC, EugeneRogov commented on app/src/main/java/com/p2p/wallet/auth/model/NameRegisterBody.kt
> +data class NameRegisterBody(
По логике response то что получаем, а этот класс для формирования запроса, если добавить response кажется что это именно ответ.

2021-10-04 13:57 UTC, EugeneRogov commented on app/src/main/java/com/p2p/wallet/auth/model/NameRegisterBody.kt
> +    data class Credentials(
Предлагаю вынести позже если класс Credentials будет переиспользоваться

2021-10-05 07:23 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/model/NameRegisterBody.kt
> +data class NameRegisterBody(
Извини, тут ошибся, хотел `request` написать. А так видел что ты добавлял `response` на модели которые получаем

2021-10-05 07:24 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/auth/model/NameRegisterBody.kt
> +    data class Credentials(
Хорошо

2021-10-05 09:43 UTC, 1sakov commented on app/src/main/java/com/p2p/wallet/infrastructure/network/NetworkModule.kt
> +        single(named(RESERVING_USERNAME_QUALIFIER)) {
@EugeneRogov насчет местоположения объекта - согласен, здесь как-будто ему не место

2021-10-05 10:03 UTC, merged