Feature/p2 pw 1226
p2p-org/p2p-wallet-android pull request #231
Opened 2022-01-31 19:15 UTC by davran1001

2022-01-31 20:03 UTC, 1sakov commented
Назови МР правильно

2022-02-01 07:35 UTC, 1sakov requested changes

2022-02-01 07:35 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
> +            } catch (e: NoSuchElementException) {
```suggestion
            val token = tokens.firstOrNull { it.symbol == symbol }
            if (token != null) items.add(token)
```

И можно убрать try catch

2022-02-01 07:35 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
> +                it.symbol.startsWith(searchText, ignoreCase = true) ||
Лучше проверять просто `it.symbol == searchText`, потому что могут быть токены с аналогичным началом, и другим концом, и проверяй только `symbol`

2022-02-01 07:37 UTC, davran1001 commented on app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
> +                it.symbol.startsWith(searchText, ignoreCase = true) ||
И получается пока пользователь полностью не введёт название правильно, он ничего не увидит ?

2022-02-01 12:19 UTC, 1sakov approved these changes

2022-02-01 12:21 UTC, merged