start history page
p2p-org/p2p-wallet-android pull request #234
Opened 2022-02-04 11:46 UTC by davran1001

2022-02-08 20:14 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/home/HomeFragment.kt
> +class HomeFragment : Fragment(R.layout.fragment_home) {
Давай фрагмент, который содержит табы и другие фрагменты будет `MainFragment`, а первый фрагмент в табе - `HomeFragment`

2022-02-09 09:12 UTC, 1sakov requested changes

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/auth/ui/username/ReserveUsernameFragment.kt
> +                setFragmentResult(REQUEST_KEY, bundleOf())
Не понял, а зачем это?

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpFragment.kt
> +        view?.isFocusableInTouchMode = true
А для чего?

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/home/MainFragment.kt
> +        // После activity.restart() поле очищается, но фрагменты есть в fragmentManager
Давай без русских комментариев

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/repository/SettingsInMemoryRepository.kt
> +class SettingsInMemoryRepository : SettingsLocalRepository {
Считаю смысла нет в этом репозитории, так как тут статичные данные, которые относятся к UI, лучше перенести эти методы в презентер, а такие репозитории использовать для хранения данных полученные из ремоута

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkFragment.kt
> +        const val REQUEST_KEY = "REQUEST_KEY_NETWORK_DIALOG"
Думаю лучше будет, если передавать `requestKey` и `resultKey` через параметры, чтобы каждый экран мог запускать этот фрагмент и ждать результат по ключу, который сам хочет

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkFragment.kt
> +        // binding.progressView.isVisible = isLoading
Вероятно метод уже не нужен

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkFragment.kt
> +                setFragmentResult(REQUEST_KEY, bundleOf(Pair(BUNDLE_KEY_IS_NETWORK_CHANGED, true)))
```suggestion
                setFragmentResult(REQUEST_KEY, bundleOf(BUNDLE_KEY_IS_NETWORK_CHANGED to true))
```

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/reset/ResetPinFragment.kt
> +        const val REQUEST_KEY = "REQUEST_KEY_RESET_PIN"
Аналогично здесь, давай передавать requestKey и resultKey снаружи

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/reset/seedphrase/ResetSeedPhraseFragment.kt
> +        const val REQUEST_KEY = "REQUEST_KEY_RESET_SEED_PHRASE"
И здесь также

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/reset/seedphrase/ResetSeedPhraseFragment.kt
> +    private fun copyPhrase() {
Давай уберем этот метод, он только на ресторе, и то должен быть удален, чтобы мы не светили сид фразы в гите

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsAdapter.kt
> +                ItemSettingsRowItemBinding.inflate(
Давай создавать биндинг внутри вьюхолдера, а здесь передавать только `parent` - это даст меньше кода в создании вьюхолдера, можешь глянуть пример в `TokenViewHolder`

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsFragment.kt
> +        setFragmentResultListener(ReserveUsernameFragment.REQUEST_KEY) { key, bundle ->
Я думаю, лучше было бы иметь один `resultListener`, только проверяем `result.containsKey` - тогда будет только один лисенер вместо трех, пример `SelectTokenFragment`

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsPresenter.kt
> +        if (!isChanged) return
А почему здесь не передавать новый выбранный network? 
Неизвестно где идет обновление

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/res/drawable/bg_element_primary_top_rounded.xml
> +        android:color="#F2F2F7" />
Юзай цвета из дизайн системы

2022-02-09 09:12 UTC, 1sakov commented on app/src/main/res/layout/fragment_home.xml
> +    android:background="?colorBackgroundPrimary"
Юзай новые цвета

2022-02-09 09:13 UTC, davran1001 commented on app/src/main/java/org/p2p/wallet/auth/ui/username/ReserveUsernameFragment.kt
> +                setFragmentResult(REQUEST_KEY, bundleOf())
после этого нужно открыть экран usernameFragment может тогда тут сделать popAndReplace ?

2022-02-09 09:14 UTC, davran1001 commented on app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpFragment.kt
> +        view?.isFocusableInTouchMode = true
для того чтоб фрагменты в стэке были не кликабельными

2022-02-09 09:14 UTC, davran1001 commented on app/src/main/java/org/p2p/wallet/home/MainFragment.kt
> +        // После activity.restart() поле очищается, но фрагменты есть в fragmentManager
окай

2022-02-10 09:16 UTC, 1sakov requested changes

2022-02-10 09:16 UTC, 1sakov approved these changes

2022-02-10 10:01 UTC, merged