[P2PW-1291] Video on Onboarding
p2p-org/p2p-wallet-android pull request #245
Opened 2022-02-14 13:03 UTC by kabramovp2p

Video (Animation) Added on Onboarding screen

2022-02-15 11:12 UTC, 1sakov requested changes

2022-02-15 11:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/auth/ui/onboarding/OnboardingFragment.kt
> +            binding.animationVideoView.start()
Давай использовать обычные lifecycle колбеки от фрагмента для контроля видео

2022-02-16 09:37 UTC, kabramovp2p commented
@1sakov обновил и пофиксил

2022-02-16 13:30 UTC, kuznetsov approved these changes

2022-02-16 14:56 UTC, 1sakov approved these changes

2022-02-16 14:56 UTC, merged