[P2PW-1263] -  Home empty state
p2p-org/p2p-wallet-android pull request #250
Opened 2022-02-16 15:17 UTC by kuznetsov

- Token color strips were removed
- Empty state is shown in home screen on account with single empty SOL token

2022-02-16 15:45 UTC, kabramovp2p requested changes
пробежал - задал вопросы и оставил комменты

2022-02-16 15:45 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/utils/ViewExtensions.kt
> +fun View.setVisible(isVisible: Boolean) {
зачем это нужно? у нас же есть Ktx

2022-02-16 15:45 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt
> +        // TODO: 15.02.2022 append SOL to account tokens and save locally
лучше всего создать задачу и описать её в джире и сюда рядом с TODO прилинковать её

2022-02-16 15:45 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
> +        swipeRefreshLayout.setVisible(!isEmpty)
почему не через ktx
balanceTextView.isVisible = !isEmpty
?

2022-02-16 15:47 UTC, kabramovp2p commented
@kuznetsov кстати а там картинка лежит одна
дизайнеры не дали нарезку? или почему она в drawable положена без dpi?

а так же png лучше не юзать
конверти плиз всё в WebP

2022-02-17 09:53 UTC, kuznetsov commented on app/src/main/res/values/colors.xml
> +    <color name="black">#000000</color>
А куда ты предлагаешь его переместить?

2022-02-17 09:55 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/utils/ViewExtensions.kt
> +fun View.setVisible(isVisible: Boolean) {
Спасибо. Пропустил этот ext и писал свой по привычке

2022-02-17 10:40 UTC, kuznetsov commented
Вижу, что в проекте сейчас все картинки лежат в одной папке без разделения на dpi. @1sakov ты так сделал для простоты? Разделение на dpi и оптимизация через webp – хорошая идея, но давайте тогда все картинки разделим и конвертируем в рамках отдельной задачи

2022-02-17 11:01 UTC, kabramovp2p commented on app/src/main/res/values/colors.xml
> +    <color name="black">#000000</color>
по идее либо ниже коммента чтобы не затёрли этот цвет либо ещё куда
но вообще не парься мне дали задачу на рефакторинг так скажем цветов так что это сделаю я =)

2022-02-17 11:04 UTC, kuznetsov commented on app/src/main/res/layout/fragment_main.xml
> +<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
Подтянул наш code style

2022-02-17 11:05 UTC, kuznetsov commented on app/src/main/res/values/colors.xml
> +    <color name="black">#000000</color>
Окей)

2022-02-17 12:12 UTC, kabramovp2p approved these changes

2022-02-17 13:25 UTC, 1sakov approved these changes

2022-02-17 13:43 UTC, merged