[P2PW-1085] ActionButtonsView animation
p2p-org/p2p-wallet-android pull request #262
Opened 2022-02-22 14:25 UTC by kuznetsov

2022-02-23 08:17 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/common/ui/widget/ActionButtonsView.kt
> +interface OnOffsetChangedListener {
Так, интерфейсы внизу класса, а вот компаньоны сверху, чтобы сразу было видно какие константы и данные в классе используются.

2022-02-23 08:17 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/common/ui/widget/ActionButtonsView.kt
> +private const val MAX_HEIGHT = 80
Согласен

2022-02-23 08:21 UTC, 1sakov requested changes

2022-02-23 08:21 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/utils/DimensionsExtensions.kt
> +fun Int.toPx() = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, this.toFloat(), Resources.getSystem().displayMetrics).toInt()
У нас есть экстеншны вроде для перевода в пиксели (dip / dipF), посмотри-ка класс `ViewExtensions`.
Если не подойдут, то можно добавить эти. 
В целом `ViewExtensions` уже достаточно большой и вероятно есть смысл оттуда принести методы в этот класс.

2022-02-23 08:22 UTC, 1sakov commented
@kuznetsov оставил немного комментариев, в целом хорошее решение!

2022-02-23 13:48 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/common/ui/widget/ActionButtonsView.kt
> +private const val MAX_HEIGHT = 80
Хороший поинт

2022-02-23 13:52 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/utils/DimensionsExtensions.kt
> +fun Int.toPx() = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, this.toFloat(), Resources.getSystem().displayMetrics).toInt()
Вижу, что ты привязываешь экстеншн к контексту, в этом есть какой-то смысл? У меня экстеншн ни от чего не зависит, удобно вызывается от Int или Float. Если определённого преимущества нет, предлагаю заменить

2022-02-23 19:05 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/utils/DimensionsExtensions.kt
> +fun Int.toPx() = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, this.toFloat(), Resources.getSystem().displayMetrics).toInt()
вот кстати интересно насколько верно юзать системные ресурсы а не ресурсы контекста... возможно если поменять размер элементов в настройках то это никак не зааффектит ресурсы системные
а вот ресурсы контекста будут меняться

2022-02-24 06:49 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/utils/DimensionsExtensions.kt
> +fun Int.toPx() = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, this.toFloat(), Resources.getSystem().displayMetrics).toInt()
Вопрос остается открытым, я так полагаю. Давайте узнаем в чем разница между системными и контектными ресурсами. 
Я всегда пользовался контекстными и проблем не имел. 
Если с системными также, то мне тоже нравится, что они простые и вызываются напрямую от типов чисел

2022-02-24 06:50 UTC, 1sakov approved these changes

2022-02-24 07:33 UTC, kabramovp2p approved these changes

2022-02-24 11:43 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/utils/DimensionsExtensions.kt
> +fun Int.toPx() = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, this.toFloat(), Resources.getSystem().displayMetrics).toInt()
Думаю, что в случае с density контекст приложения не играет роли, так как речь о системном значении экрана телефона. Предлагаю смерджить так, как есть и завести задачу на ресёрч и замену в других местах

2022-02-24 13:42 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/utils/DimensionsExtensions.kt
> +fun Int.toPx() = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, this.toFloat(), Resources.getSystem().displayMetrics).toInt()
Окей, давай

2022-02-24 13:55 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/utils/DimensionsExtensions.kt
> +fun Int.toPx() = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, this.toFloat(), Resources.getSystem().displayMetrics).toInt()
Да

2022-02-24 13:55 UTC, merged