[P2PW-1335] Main screen redesign
p2p-org/p2p-wallet-android pull request #282
Opened 2022-02-25 15:34 UTC by kuznetsov

2022-02-25 15:46 UTC, kabramovp2p approved these changes
заапрувил, но внёс предложение

2022-02-25 15:46 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
> +        val title = requireContext().run {
val title = requireContext().getString(
                    if (item.isHiddenTokens) R.string.main_hidden_tokens
                    else R.string.main_active_tokens
                )

2022-02-25 15:55 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
> +        val title = requireContext().run {
Да, хороший комментарий

2022-02-25 19:45 UTC, 1sakov requested changes

2022-02-25 19:45 UTC, 1sakov commented on app/src/main/res/layout/item_token.xml
> +        android:paddingStart="18dp"
Отступы должны быть кратными 4-ем

2022-02-25 19:45 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
> +            itemView.setOnClickListener { listener.onToggleClicked() }
А почему клик ставим только если `isHiddenTokens`, а не всегда?

2022-02-25 19:45 UTC, 1sakov commented on app/src/main/res/layout/item_banners.xml
> +    android:paddingHorizontal="14dp"
Здесь тоже должен быть кратным 4-ем. Если так в дизайне, то надо в дизайне изменить, потому что это нарушение гайдлайнов на андроиде

2022-02-25 19:45 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapter.kt
> +        add(0, HomeElementItem.Action(state, isHidden))
Это не сломало ничего?

2022-02-26 18:16 UTC, kuznetsov commented on app/src/main/res/layout/item_token.xml
> +        android:paddingStart="18dp"
Поменял горизонтальные отступы на 16px,  написал об этом дизайнеру

2022-02-26 18:16 UTC, kuznetsov commented on app/src/main/res/layout/item_banners.xml
> +    android:paddingHorizontal="14dp"
Здесь тоже поставил кратное 4 значение

2022-02-26 18:17 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
> +            itemView.setOnClickListener { listener.onToggleClicked() }
По дизайну добавился заголовок Tokens над активными токенами. Он не кликабельный, по его нажатию активные токены не схлопываются

2022-02-26 18:18 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapter.kt
> +        add(0, HomeElementItem.Action(state, isHidden))
Нет, это добавляет _Tokens_ для активных токенов и _Hidden tokens_ для скрытых

2022-02-28 05:32 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
> +            itemView.setOnClickListener { listener.onToggleClicked() }
Ну он раньше тоже был некликабельный. Этот вьхолдер использовался только про заголовок `Hidden tokens` после активных токенов. 
Проверь плз скрытие и показ скрытых токенов нормально ли отрабатывает

2022-02-28 08:08 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
> +            itemView.setOnClickListener { listener.onToggleClicked() }
Условие `if (item.isHiddenTokens)` как раз про скрытые токены. Не по состоянию, а типу токенов. Клик на Hidden tokens отрабатывает корректно

2022-02-28 08:55 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
> +            itemView.setOnClickListener { listener.onToggleClicked() }
Хорошо

2022-02-28 08:56 UTC, 1sakov commented
@kuznetsov тесты упали, у тебя сборка не собирается:
```/home/circleci/app/app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapter.kt: (38, 45): Overload resolution ambiguity: 
public constructor TokenButtonViewHolder(binding: [ERROR : ItemTokenHiddenGroupButtonBinding], listener: OnHomeItemsClickListener) defined in org.p2p.wallet.home.ui.main.adapter.TokenButtonViewHolder
public constructor TokenButtonViewHolder(parent: ViewGroup, listener: OnHomeItemsClickListener) defined in org.p2p.wallet.home.ui.main.adapter.TokenButtonViewHolder
e: /home/circleci/app/app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt: (8, 35): Unresolved reference: ItemTokenHiddenGroupButtonBinding
e: /home/circleci/app/app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt: (14, 14): Unresolved reference: ItemTokenHiddenGroupButtonBinding
e: /home/circleci/app/app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt: (22, 19): Unresolved reference: ItemTokenHiddenGroupButtonBinding
e: /home/circleci/app/app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt: (35, 23): Variable expected
e: /home/circleci/app/app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt: (36, 24): Variable expected```

2022-02-28 08:56 UTC, 1sakov approved these changes

2022-02-28 12:54 UTC, merged