[P2PW-1437] Handle renBtc session statuses
p2p-org/p2p-wallet-android pull request #314
Opened 2022-03-02 18:33 UTC by davran1001

2022-03-02 18:59 UTC, 1sakov requested changes

2022-03-02 18:59 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcPresenter.kt
> +                view?.showLoading(session is RenBtcSession.Loading)
Я бы все-таки добавил `Loading` в `when`, и вызывал `view?.showLoading` в каждом статусе с нужным значением.
Вероятно, вдобавок, у тебя тут уже горит варнинг, потому что sealed класс не содержит всех трех значений.
Ну и читабельнее имхо

2022-03-02 18:59 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcPresenter.kt
> -            delay(ONE_SECOND_IN_MILLIS)
Кажется эту константу можно удалять

2022-03-02 18:59 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/renbtc/RenBtcModule.kt
> +        single { RenBtcRoomRepository(get()) } bind RenBtcDaoRepository::class
Нейминг следующий:
`RenBtcRoomRepository` -> `RenBtcDatabaseRepository`
`RenBtcDaoRepository` -> `RenBtcLocalRepository`

2022-03-02 18:59 UTC, 1sakov commented on solanaj/src/main/java/org/p2p/solanaj/core/PublicKey.kt
> +        Log.d("#####_KEY", pubkey)
забыл убрать

2022-03-02 18:59 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/renbtc/ui/main/RenBTCPresenter.kt
> +        launch {
пустая корутина

2022-03-02 18:59 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/renbtc/interactor/RenBtcInteractor.kt
> +    suspend fun saveSession(session: RenBtcSession) {
Я бы назвал `setSessionState`, так как ты здесь не только сохраняешь, но и прокидываешь `Loading` и `Error` стейты

2022-03-02 18:59 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/renbtc/interactor/RenBtcInteractor.kt
> +            }
Может уберем фигурные скобки, если у нас только однострочный вызов? 
Уменьшится все это до 2 строчек и читабельнее будет
Выше где-то тоже было

2022-03-02 18:59 UTC, 1sakov commented
@davran1001 оставил немного комментов

2022-03-02 19:08 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/renbtc/interactor/RenBtcInteractor.kt
> +            }
так да по идее и надо так если одна то они лишние

2022-03-02 19:09 UTC, kabramovp2p approved these changes
вроде норм если поправишь что написал @1sakov

2022-03-02 19:44 UTC, kuznetsov approved these changes

2022-03-02 19:44 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcFragment.kt
> +    }
Кодстайл и сейчас, наверное, не очень важно, но я бы писал
```suggestion
    override fun showErrorMessage(e: Throwable?) = showErrorDialog(e) {
        popBackStack()
    }
```

2022-03-02 19:44 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/renbtc/repository/RenBtcRoomRepository.kt
> +        return dao.getSessionFlow(destinationAddress).map { session ->
Лишний return
```suggestion
    override fun findSessionFlow(destinationAddress: String) = dao.getSessionFlow(destinationAddress).map { session ->
```

2022-03-02 19:44 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/renbtc/repository/RenBtcRoomRepository.kt
> +        return dao.findByDestinationAddress(destinationAddress)?.let {
Ещё один return

2022-03-03 09:13 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcPresenter.kt
> +                view?.showLoading(session is RenBtcSession.Loading)
Убирать надо будет в каждом стейте кроме Loading

2022-03-03 09:25 UTC, 1sakov approved these changes

2022-03-03 18:47 UTC, merged