P2PW-1484 - do not show info warning block on transfering SOL tokens
p2p-org/p2p-wallet-android pull request #347
Opened 2022-03-13 11:34 UTC by kabramovp2p

2022-03-13 11:38 UTC, gslevinkov approved these changes

2022-03-13 11:38 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
> +            view?.showAccountFeeView(null, token?.isSOL == true)
при работе с null или булевскими параметрами лучше добавлять named arg к аргументам. вот я сейчас вижу вызов этого метода, но не понимаю какой тип у первого параметра и что должно передаваться во второй. придется идти смотреть в реализацию. а с именованными параметрами будет ясно что передается как null и какая проверка пойдет вторым параметром

2022-03-13 11:38 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
> +    suspend fun getBalance(address: String): Long = rpcRepository.getBalance(address)
пасебо!!

2022-03-13 11:39 UTC, gslevinkov commented
"Формат коммита должен полностью совпадать с название ПР"
у тебя не хватает тире в коммите

2022-03-13 11:39 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
> +            view?.showAccountFeeView(null, token?.isSOL == true)
согласен
давай так договоримся
мы правим старый код или нет + по кодстайлу мы пока так и не решили что делаем (

2022-03-13 11:40 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
> +            view?.showAccountFeeView(null, token?.isSOL == true)
слушай, ну я бы не сказал что это старый код
ты потрогал же уже строчку, можно свободно добавить named arg как часть изменений

2022-03-13 11:40 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
> +            view?.showAccountFeeView(null, token?.isSOL == true)
в этом презенторе 6 подобных вызов 
по этому я и спросил
ибо я лучше везде поменяю

2022-03-13 11:41 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
> +            view?.showAccountFeeView(null, token?.isSOL == true)
ну импакта большого нет (да и вообще как такого), изменения не большие. я бы тут воспользовался правилом бойскаута

2022-03-13 11:42 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
> +            view?.showAccountFeeView(null, token?.isSOL == true)
тогда меняю везде )

2022-03-13 11:49 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
> +            view?.showAccountFeeView(null, token?.isSOL == true)
@gslevinkov `DonЪ`

2022-03-13 19:22 UTC, 1sakov commented
Почему-то не вижу фиксов по описанию задачи и трем комментариям. 
Фикс только на СОЛ и это не совсем то, что нужно делать.

Блок комиссии за создание аккаунта показывается, если аккаунт по введенному адресу не найден. 
Получается, пользователь вводит адрес пользовательского СОЛа, у которого существует кошелек, значит проверка адреса на СОЛ работает неправильно, и нужно сделать фикс, глубже. 

Фикс по `isSourceSol` - уже костыль

2022-03-13 19:29 UTC, 1sakov requested changes

2022-03-13 19:29 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
> +            view?.showAccountFeeView(fee = null, isSourceSOL = token?.isSOL == true)
Почему-то не вижу фиксов по описанию задачи и трем комментариям.
Фикс только на СОЛ и это не совсем то, что нужно делать.

Блок комиссии за создание аккаунта показывается, если аккаунт по введенному адресу не найден.
Получается, пользователь вводит адрес пользовательского СОЛа, у которого существует кошелек, значит проверка адреса на СОЛ работает неправильно, и нужно сделать фикс, глубже.

Фикс по `isSourceSol` - уже костыль.

Предлагаю завтра созвониться и обсудить задачу

2022-03-25 13:59 UTC, kuznetsov approved these changes

2022-03-31 09:33 UTC, merged