PWN-3169 - Fix cached user error on send
p2p-org/p2p-wallet-android pull request #400
Opened 2022-03-31 10:52 UTC by kuznetsov

[Jira ticket](https://p2pvalidator.atlassian.net/browse/PWN-3169)

Disable cache on getting account info from send screen.

![Error screenshot](https://cdn.discordapp.com/attachments/828949357276430336/958379643994517534/unknown.png)

2022-03-31 11:26 UTC, 1sakov requested changes

2022-03-31 11:26 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/rpc/interactor/TransactionAddressInteractor.kt
> +        val accountInfo = userAccountRepository.getAccountInfo(associatedAddress.toBase58(), useCache)
Фикс не здесь, а в методе `findSplTokenAddress`

2022-03-31 11:53 UTC, 1sakov commented
А почему описание не шаблону?

2022-03-31 13:38 UTC, kuznetsov commented
> А почему описание не шаблону?

Fixed

2022-03-31 14:58 UTC, 1sakov approved these changes

2022-04-01 09:49 UTC, gslevinkov approved these changes

2022-04-01 10:24 UTC, kabramovp2p approved these changes

2022-04-15 10:45 UTC, merged