PWN-3775 - Fix restore key button state
p2p-org/p2p-wallet-android pull request #534
Opened 2022-06-14 12:07 UTC by davran1001

## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-3775

2022-06-14 13:24 UTC, gslevinkov approved these changes

2022-06-14 22:12 UTC, 1sakov requested changes

2022-06-14 22:12 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/restore/ui/keys/SecretKeyFragment.kt
> -        setButtonEnabled(phraseAdapter.itemCount != 0)
We need to enable the button if we navigated back to this screen. 
I think we shouldn't delete it but add check for `phraseAdapter.itemCount == 12 or 24`

2022-06-16 07:41 UTC, kabramovp2p approved these changes

2022-06-17 10:18 UTC, kuznetsov approved these changes

2022-06-20 08:56 UTC, 1sakov approved these changes

2022-06-20 08:56 UTC, merged