PWN-4120 Swap button status fix
p2p-org/p2p-wallet-android pull request #584
Opened 2022-07-07 13:14 UTC by kuznetsov

### Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-4120

### Description of Work

- Fixed swap button status by updating it even if destination is still not chosen.
- Removed duplicating code in `fillMaxAmount()`

2022-07-08 07:55 UTC, gslevinkov approved these changes

2022-07-08 07:55 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
> +        setSourceAmount(amount, true)
named arg plz

2022-07-08 08:20 UTC, kabramovp2p approved these changes

2022-07-11 20:24 UTC, 1sakov requested changes

2022-07-11 20:24 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/swap/model/SwapButton.kt
> -                !isValidDestination -> State.Disabled(R.string.swap_choose_the_destination)
Тут надо вернуть. 
Он сначала должен на пары и баланс проверить, а потом уже на destination

2022-07-11 20:24 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
> -        findValidFeePayer(CORRECT_AMOUNT, destination, desiredFeePayerToken = sourceToken)
Здесь тоже разломал. 
Если пользователь нажал на max, то в случае, если солов нет, мы должен уменьшить сумму инпута

2022-07-14 11:51 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
> -        findValidFeePayer(CORRECT_AMOUNT, destination, desiredFeePayerToken = sourceToken)
Is this about the button status? Maybe that's another task?

2022-07-14 20:36 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
> -        findValidFeePayer(CORRECT_AMOUNT, destination, desiredFeePayerToken = sourceToken)
no, it's not.
There is selection mechanism is implemented and if you fix this button, you'll break the fee payer token logic. 
So, it's not right to make it as another task, please fix it here

2022-07-15 09:39 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
> -        findValidFeePayer(CORRECT_AMOUNT, destination, desiredFeePayerToken = sourceToken)
I've got you. Fixed the issue

2022-07-15 09:48 UTC, 1sakov approved these changes

2022-07-15 09:49 UTC, merged