PWN-4614 - Critical error screen for onboarding flow
p2p-org/p2p-wallet-android pull request #670
Opened 2022-08-19 11:00 UTC by gslevinkov

## Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-4614

## Description of Work

## Screenshots (Optional)

Screenshot #1 |
:------------:|
<img width="393" alt="Screen Shot 2022-08-19 at 13 59 19" src="https://user-images.githubusercontent.com/100791035/185604487-c51ee8f5-d47d-4b59-af42-e65d3ff4d8d4.png"> |

2022-08-22 10:43 UTC, 1sakov requested changes

2022-08-22 17:56 UTC, kabramovp2p commented on app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt
> +                    result.message?.let {
let but do not use it?

2022-08-22 17:56 UTC, kabramovp2p approved these changes

2022-08-23 07:40 UTC, gslevinkov commented on app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt
> +                    view?.showErrorSnackBar(R.string.error_general_message)
on any error except some, we show general message

2022-08-23 08:56 UTC, 1sakov approved these changes
good job, well done!

2022-08-23 09:04 UTC, merged