PWN-4616 Restore onboarding flow on pin creation
p2p-org/p2p-wallet-android pull request #681
Opened 2022-08-23 15:19 UTC by kuznetsov

### Jira Ticket

https://p2pvalidator.atlassian.net/browse/PWN-4616

### Description of Work

Navigate to pin code creation if user left onboarding on this step

2022-08-23 18:37 UTC, kabramovp2p approved these changes

2022-08-24 05:05 UTC, 1sakov requested changes

2022-08-24 05:05 UTC, 1sakov approved these changes

2022-08-24 05:23 UTC, gslevinkov approved these changes

2022-08-24 11:27 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootPresenter.kt
> +        return tokenKeyProvider.secretKey.isNotEmpty() && !authInteractor.isAuthorized()
secretKey instance guarantees us the user got all 3 shares, cause account is creating after otp confirmation

2022-08-24 11:27 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
> +        addToBackStack = false
@kabramovp2p @gslevinkov guys could you help me with that?

2022-08-24 12:05 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootPresenter.kt
> +        return tokenKeyProvider.secretKey.isNotEmpty() && !authInteractor.isAuthorized()
ah, got it!

2022-08-24 12:09 UTC, 1sakov commented on app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
> +        addToBackStack = false
you have to call `popAndReplace` on the next screen.
for example: 

`previous screen` - `OnboardingRootFragment` - `next screen` - `target screen`

if you want the user to navigate from `next screen` to `target screen` and by clicking on back on `target screen` you want the user to be on `previous screen` you should call: 

popAndReplace(target = `target screen`, popTo=`previous screen`)

In that case you'll skip the `OnboardingRootFragment` without manipulations with backstack

2022-08-24 15:42 UTC, kuznetsov commented on app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
> +        addToBackStack = false
I've got it. We can consider changing onboarding navigation

2022-08-25 07:39 UTC, merged